import { ethers } from 'ethers'

// IMPORTANT: Do not change this message again.
//
// The user's auto-wallet address is deterministically derived from the wallet
// signature over this exact message. Changing the message changes the derived
// auto-wallet address, which can strand funds in the previously derived wallet.
//
// This restores the original Version: 2 message so each main wallet maps back
// to its original funded auto-wallet.
export const MASTER_SEED_MESSAGE =
  'MediVault \u2014 unlock my health vault and auto-wallet.\n\n' +
  'Signing this single message generates the AES-256 key that encrypts your records ' +
  'and creates the background wallet that pays 0G gas fees. ' +
  'Only your wallet can reproduce these keys.\n\nVersion: 2'

// The master-seed signature is the root secret. We keep it ONLY in memory.
// Previously it was stored in sessionStorage which exposed it to XSS attacks.
// Now a page refresh will require the user to re-sign the wallet message,
// which is a small UX cost for significantly better security.
let cachedMasterSeed: string | null = null

export function clearMasterSeed() {
  cachedMasterSeed = null

  // Clean up any legacy sessionStorage entries from previous versions.
  try {
    if (typeof window !== 'undefined') {
      const LEGACY_PREFIX = 'medivault_seed_v2'
      for (let i = sessionStorage.length - 1; i >= 0; i--) {
        const k = sessionStorage.key(i)
        if (k && k.startsWith(LEGACY_PREFIX)) sessionStorage.removeItem(k)
      }
    }
  } catch {}
}

async function getMasterSeed(signer: ethers.Signer): Promise<string> {
  if (cachedMasterSeed) return cachedMasterSeed

  // The seed is no longer persisted to any storage. The user must re-sign on
  // page refresh. This prevents XSS from exfiltrating the root secret via
  // sessionStorage.
  cachedMasterSeed = await signer.signMessage(MASTER_SEED_MESSAGE)
  return cachedMasterSeed
}

/**
 * Derive the stable legacy 32-byte AES-256 vault key from the wallet signature.
 *
 * This intentionally preserves the original derivation so existing encrypted
 * records remain decryptable for users who already uploaded data.
 */
export async function deriveVaultKey(
  signer: ethers.Signer,
): Promise<Uint8Array> {
  const seed = await getMasterSeed(signer)
  const digest = ethers.keccak256(ethers.toUtf8Bytes(seed + ':vault'))
  return ethers.getBytes(digest) // 32 bytes
}

/**
 * Recover the public key of the signer from the master seed signature.
 */
export async function recoverUserPublicKey(
  signer: ethers.Signer,
): Promise<string> {
  const seed = await getMasterSeed(signer)
  const messageHash = ethers.hashMessage(MASTER_SEED_MESSAGE)
  return ethers.SigningKey.recoverPublicKey(messageHash, seed)
}

/**
 * Derive the stable deterministic private key for the Auto-Wallet.
 *
 * DO NOT change this derivation without a migration flow. Funds may already be
 * sitting in the address generated by this exact formula.
 */
export async function deriveAutoWalletPk(
  signer: ethers.Signer,
): Promise<string> {
  const seed = await getMasterSeed(signer)
  const digest = ethers.keccak256(ethers.toUtf8Bytes(seed + ':auto-wallet'))
  return digest // 0x... hex string suitable for ethers.Wallet
}

/** Stable per-owner stream id for the 0G-KV index. */
export function deriveStreamId(owner: string): string {
  return ethers.keccak256(
    ethers.toUtf8Bytes(`medivault:index:${owner.toLowerCase()}`),
  )
}

/**
 * Derive a per-record AES-256 key from the wallet master key + a fresh salt.
 *
 * Each uploaded record gets its own 32-byte key via HKDF-SHA256 so that
 * compromising one record's key never reveals any other record. The salt is
 * stored (in the clear \u2014 it is not secret) in RecordMeta so the key can be
 * reproduced on download.
 *
 * Records written before this field existed have no salt and continue to use
 * the master key directly (see recordKey()).
 */
export async function deriveRecordKey(
  masterKey: Uint8Array,
  salt: Uint8Array,
): Promise<Uint8Array> {
  if (masterKey.byteLength !== 32) throw new Error('master key must be 32 bytes')
  if (salt.byteLength !== 16) throw new Error('salt must be 16 bytes')
  const keyMaterial = await crypto.subtle.importKey(
    'raw',
    masterKey as BufferSource,
    { name: 'HKDF' },
    false,
    ['deriveBits'],
  )
  const bits = await crypto.subtle.deriveBits(
    {
      name: 'HKDF',
      hash: 'SHA-256',
      salt: salt as BufferSource,
      info: new TextEncoder().encode('medivault/record-key/v1') as BufferSource,
    },
    keyMaterial,
    256,
  )
  return new Uint8Array(bits)
}

/** Generate a fresh 16-byte record salt. */
export function newRecordSalt(): Uint8Array {
  return crypto.getRandomValues(new Uint8Array(16))
}

/**
 * Resolve the AES key to use for a given record. If the record carries a salt,
 * a per-record key is derived; otherwise (legacy records) the master key is
 * returned unchanged so old uploads remain decryptable.
 */
export async function recordKey(
  masterKey: Uint8Array,
  recordKeySalt?: string | null,
): Promise<Uint8Array> {
  if (!recordKeySalt) return masterKey
  const salt = hexToBytes(recordKeySalt)
  return deriveRecordKey(masterKey, salt)
}

function hexToBytes(hex: string): Uint8Array {
  const h = hex.startsWith('0x') ? hex.slice(2) : hex
  const bytes = new Uint8Array(h.length / 2)
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = parseInt(h.substr(i * 2, 2), 16)
  }
  return bytes
}

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('')
}

/** Hex-encode a salt for storage in RecordMeta. */
export function saltToHex(salt: Uint8Array): string {
  return bytesToHex(salt)
}

/**
 * Content address (keccak-256) of the raw, pre-encryption file bytes. Used to
 * detect duplicate uploads of the exact same document. This is computed over
 * plaintext locally and never leaves the device; only the resulting hash is
 * stored in RecordMeta.
 */
export function contentHashHex(bytes: Uint8Array): string {
  return ethers.keccak256(bytes)
}

/** Encode a string key into bytes for 0G-KV. */
export function kvKeyBytes(key: string): Uint8Array {
  return ethers.toUtf8Bytes(key)
}

/** The reserved KV key that stores the list of record ids for an owner. */
export const KV_INDEX_LIST_KEY = '__medivault_record_ids__'
